### ISSUE TITLE
minimal example

### ISSUE THREAD

**Issue by m1ci** [nclozza/MI_DDW_Seminar_work#1]
In the README you write to download the XML dump.
Section requirements: https://github.com/nclozza/MI_DDW_Seminar_work/blob/master/README.md#requirements

Maybe instead of requesting a download of an XML dump can you maybe provide a small dump which can be used for testing purposes? Lets say 10-20 MB dump.

**Comment by m1ci** [comment]
or create a script such as this one
https://github.com/dbpedia/extraction-framework/blob/master/dump/src/test/bash/createMinidump.sh
which will create minimal dump on the fly.

**Comment by nclozza** [comment]
Yes, I'll upload it when it's done!

**Comment by nclozza** [comment]
Done.

The file is `test_dump.xml` and it's in `src/data`
